{% set name = "sshtk" %}
{% set version = "0.2.0" %}
{% set sha256 = "7d2f3456731fbd6218b0b3698e0a2cac5e0720597693c0aae48f40c1dcac6a3a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ohmeta/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pyotp
    - pexpect

test:
  commands:
    - sshtk.py --help
    - sshtk.py login --help
    - sshtk.py tunel --help
    - sshtk.py dl --help
    - sshtk.py up --help

about:
  home: https://github.com/ohmeta/sshtk
  summary: 'SSH toolkit'
  license: GPL3
  license_family: GPL

extra:
  recipe-maintainers:
    - alienzj
